#!/usr/bin/python3
import hashlib
import time
import sys

def startBy(s):
	n = 0
	index = -1
	for i in range(len(s)):
		if s[i] == "0":
			n += 4
		else:
			index = i
			break
	if index > 0:
		if s[index] == "1":
			n += 3
		elif s[index] in "23":
			n += 2
		elif s[index] in "4567":
			n += 1
	return n


if __name__=="__main__":
	s = ""
	h = ""
	header = sys.argv[1]
	file = sys.argv[2]


	with open(file, "rb") as f:
		s = f.read()
	with open(header, "r") as f:
		h = f.read()


	initialhash = hashlib.sha256(s).hexdigest()
	initialhash_original = h.splitlines()[1].split(": ")[1]
	if initialhash != initialhash_original:
		print(f"fail, initialhash does not match:\nExpected:{initialhash}\nShown in the output: {initialhash_original}")
		sys.exit(0)

	prefix = h.splitlines()[2].split(": ")[1]
	Hash = hashlib.sha256((prefix + initialhash).encode()).hexdigest()
	Hash_original = h.splitlines()[3].split(": ")[1]
	if Hash != Hash_original:
		print(f"fail, Hash does not match:\nExpected:{Hash}\nShown in the output: {Hash_original}")
		sys.exit(0)

	numLeadingBits = startBy(Hash)
	numLeadingBits_original = int(h.splitlines()[4].split(": ")[1])
	if numLeadingBits != numLeadingBits_original:
		print(f"fail, leading-bits does not match:\nExpected:{numLeadingBits}\nShown in the output: {numLeadingBits_original}")
		sys.exit(0)

	print("pass")