#!/usr/bin/python3
import sys
def random_seed(x):
	return (x*109 + 57) % 256

def map_chr(password):
	hash_val = 0
	for i in range(len(password)):
		c = password[i]
		hash_val = ord(c) + (hash_val << 6) + (hash_val << 16) - hash_val
	return hash_val

def encrypt(password, plaintext, ciphertext):
	chunk_size = 16
	byte_size = 256
	g = open(plaintext, encoding="latin-1")
	def read_chunk():
		return g.read(chunk_size)

	def shuffle_key_stream(key_stream):
		def swap(i, j):
			tmp = key_stream[i]
			key_stream[i] = key_stream[j]
			key_stream[j] = key_stream[i]
		for i in range(len(key_stream)):
			first = key[i]&0xf
			second = (key[i]>>4) & 0xf
			swap(first, second)

	def process_chunk(chunk, ciphertext_block, key_byte):
		output = b""
		not_pad = True
		new_cipher_text = []
		if type(chunk) is list:
			bchunk = chunk 
		else:
			bchunk = list(bytes(chunk, 'latin-1'))

		if len(bchunk) !=16:
			not_pad = False
			k = 16 - len(bchunk)
			while len(bchunk) < 16:
				bchunk.append(k)
		key_stream = []
		if ciphertext_block == []:
			for i in range(16):
				key_byte = random_seed(key_byte)
				ciphertext_block.append(key_byte)

		for i in range(16):
			key_byte = random_seed(key_byte)
			key_stream.append(key_byte)

		for i in range(len(bchunk)):
			plain_byte = bchunk[i]
			cipher_byte = ciphertext_block[i]
			key_b = key_stream[i]
			res = (plain_byte^cipher_byte)^key_b
			new_cipher_text.append(res)
			output += res.to_bytes(1, byteorder="little")

		return output ,new_cipher_text, key_byte, not_pad

	with open(ciphertext, 'w') as f:
		f.write("")
	key_byte = map_chr(password)
	new_cipher_text = []
	for chunk in iter(read_chunk, ''):
		new_str, new_cipher_text, key_byte, not_pad = process_chunk(chunk, new_cipher_text, key_byte)
		with open(ciphertext, 'ab') as f:
			f.write(new_str)

	if not_pad:
		new_str, new_cipher_text, key_byte, _ = process_chunk([16]*16, new_cipher_text, key_byte)
		with open(ciphertext, 'ab') as f:
			f.write(new_str)

if __name__=="__main__":
	if len(sys.argv) != 4:
		print("incorrect arguments")
		sys.exit(1)

	_, password, plaintext, ciphertext = sys.argv

	encrypt(password, plaintext, ciphertext)



